query eventContentTypeCollection {
  eventContentTypeCollection {
    items {
      eventTitle
      eventSlug
      eventDisplayImage {
        url
      }
      eventSearchTags
      eventLocation
      eventDates
      eventType
    }
  }
}
